hash: disallow sri/base64/typed hashes
Special patch for ofborg evaluation to ensure nixpkgs is backwards
compatible with nix 2.0, which is what's currently stated as the minimum
version requirement to evaluate master.

    nix-repl> :b fetchurl { url = "https://example.org"; sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="; }
    error: hash 'sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=' is not backwards compatible, SRI hashes are not allowed in nixpkgs yet